// Regenerate contracts/WickGunBodies.sol from web/gunart.js so the on-chain
// gun drawings stay byte-identical to the site's. Run after editing gunart.js,
// then `npm run compile`.
import { readFileSync, writeFileSync } from "fs";
import vm from "vm";

const src = readFileSync("web/gunart.js", "utf8");

// evaluate each string-constant expression from the IIFE in isolation
function grab(name) {
  const re = new RegExp("const " + name + " =([\\s\\S]*?);\\n", "m");
  const m = src.match(re);
  if (!m) throw new Error(name + " not found in gunart.js");
  return vm.runInNewContext("(" + m[1] + ")", {});
}
const bodies = { B_PISTOL: "PISTOL", B_SMG: "SMG", B_SHOT: "SHOTGUN", B_RIFLE: "RIFLE", B_HEAVY: "HEAVY", B_CANNON: "CANNON" };
// OV is an object literal { 11: "...", ... }
const ovSrc = src.match(/const OV = \{([\s\S]*?)\n\};/m);
if (!ovSrc) throw new Error("OV not found");
const OV = vm.runInNewContext("({" + ovSrc[1] + "})", {});

let consts = "";
for (const [sol, js] of Object.entries(bodies)) {
  const v = grab(js);
  if (v.includes('"')) throw new Error(js + " contains a double quote — not Solidity-safe");
  consts += `  string private constant ${sol} = "${v}";\n`;
}
for (const k of [11, 12, 13, 14, 15]) {
  const v = OV[k];
  if (v.includes('"')) throw new Error("OV" + k + " contains a double quote");
  consts += `  string private constant OV${k} = "${v}";\n`;
}

const sol = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/*
  WickGunBodies - the vector gun drawings + 1/1 overlays for WICK Arsenal.
  GENERATED by sync-bodies.mjs from web/gunart.js - do not edit by hand.
  Split from WickGunArt purely for the 24KB contract size limit.
*/
contract WickGunBodies {
${consts}
  function body(uint8 t) external pure returns (string memory) {
    if (t == 2) return B_SMG;
    if (t == 3) return B_SHOT;
    if (t == 4 || t == 13 || t == 14) return B_RIFLE;
    if (t == 5) return B_HEAVY;
    if (t == 15) return B_CANNON;
    return B_PISTOL;
  }
  function ov(uint8 t) external pure returns (string memory) {
    if (t == 11) return OV11;
    if (t == 12) return OV12;
    if (t == 13) return OV13;
    if (t == 14) return OV14;
    if (t == 15) return OV15;
    return "";
  }
}
`;
writeFileSync("contracts/WickGunBodies.sol", sol);
console.log("WickGunBodies.sol regenerated from gunart.js (" + sol.length + " bytes)");
